config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/pages/home')

  get 'pages/home'

  devise_for :users, controllers: { registrations: "registrations" } 

  resources :users, :only => :none do
    resources :profiles
  end

  resources :addresses

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user

  enum state: [:AL, :AK, :AS, :AZ, :AR, :CA, :CO, :CT, :DE, :DC, :FL, :GA, :GU, :HI, :ID, :IL, :IN, :IA, :KS, :KY, :LA, :ME, :MD, :MH, :MA, :MI, :FM, :MN, :MS, :MO, :MT, :NE, :NV, :NH, :NJ, :NM, :NY, :NC, :ND, :MP, :OH, :OK, :OR, :PW, :PA, :PR, :RI, :SC, :SD, :TN, :TX, :UT, :VT, :VA, :VI, :WA, :WV, :WI, :WY]
  enum type: [:home, :work, :other]
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessor :first_name, :middle_name, :maiden_name, :last_name, :birthday, :gender

  enum gender: [:"", :female, :male, :other]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :addresses
  has_many :profiles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end

  def create
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end

  def new
    @user = current_user
    @profile = Profile.new
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def show
  end

  def create
    @profile = current_user.profiles.new(profile_params)
    if @profile.save!
      redirect_to pages_home_path
    else
      render "new"
    end
  end

  def update
  end

    private

    def profile_params
      params.require(:profile).permit(:first_name, :middle_name, :maiden_name, :last_name, :gender, :birthday)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    "/users/#{current_user.id}/profiles/new"
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/personal_info_helper.rb
module PersonalInfoHelper
end

app/views/addresses/create.html.erb
<h1>Addresses#create</h1>
<p>Find me in app/views/addresses/create.html.erb</p>

app/views/addresses/edit.html.erb
<h1>Addresses#edit</h1>
<p>Find me in app/views/addresses/edit.html.erb</p>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1>Addresses#new</h1>
<p>Find me in app/views/addresses/new.html.erb</p>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/addresses/update.html.erb
<h1>Addresses#update</h1>
<p>Find me in app/views/addresses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FamilyShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"> Family Share </a>
      </div>
      <div class="collapse navbar-collapse">
        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <% if current_user.profiles.size > 0 %>
          <li class="active"><a href="/users/<%= current_user.id %>/profiles/<%= current_user.profiles.first.id%>/edit">My Profile</a></li>
          <% end%>
          <li><a href="/addresses">Addresses</a></li>
        </ul>
        <p class="navbar-text pull-right">
          
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'My Account', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class =>'navbar-link' %>
          <% else %>
          <p class="navbar-text pull-right">
            <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link' %> | <%= link_to 'Login', new_user_session_path, :class => 'navbar-link' %>
          <% end %>
        </p>
      </div>
    </div>
  </nav>
  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %> </p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %> </p>
    <% end %>
    <%= yield %>
  </div>
  <footer>
    <div class="container">
      Susan Schmidt 2015
    </div>
  </footer>
</body>
</html>

app/views/pages/home.html.erb
<!-- <img class="img-responsive" src="http://www.publicdomainpictures.net/download-picture.php?adresar=30000&soubor=cork-board.jpg" alt="corkboard"> -->
<div class="corkboard">
  <%= link_to image_tag("blue_pi.png"), addresses_path %>
</div>

app/views/profiles/create.html.erb
<h1>Profile#create</h1>
<p>Find me in app/views/profile/create.html.erb</p>

app/views/profiles/edit.html.erb
<h2>Edit my profile</h2>

<%= form_for @profile, url: {action: "update"} do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name%>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender, Profile.genders.keys %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>


<%= link_to "Back", :back %>

app/views/profiles/index.html.erb
<h1>Profile#index</h1>
<p>Find me in app/views/profile/index.html.erb</p>

app/views/profiles/new.html.erb
<h2>My Profile</h2>

<%= form_for @profile, url: {action: "create"} do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name%>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender, Profile.genders.keys %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>


<%= link_to "Back", :back %>

app/views/profiles/show.html.erb
<h1>Profile#show</h1>
<p>Find me in app/views/profile/show.html.erb</p>

app/views/profiles/update.html.erb
<h1>Profile#update</h1>
<p>Find me in app/views/profile/update.html.erb</p>